name: Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: book-loan-david-yalin
  REGION: us-central1
  SERVICE: book-loan-service
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/book-loan-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image (linux/amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
          platforms: linux/amd64

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE }}
          region: ${{ env.REGION }}
          allow-unauthenticated: true
          port: 8080